-- Questao 1
CREATE SEQUENCE SQ_EMPLOYEE_PK INCREMENT BY 2 START WITH 2;
CREATE TABLE employee(
	id INTEGER PRIMARY KEY DEFAULT NEXTVAL('SQ_EMPLOYEE_PK'),
	name VARCHAR(30)
);
INSERT INTO employee(name) VALUES('Jose');
INSERT INTO employee(name) VALUES('Roberto');
INSERT INTO employee(name) VALUES('Junior');
INSERT INTO employee(name) VALUES('Bernard');
INSERT INTO employee(name) VALUES('THiago');
SELECT * FROM employee;

-- Questao 2
CREATE OR REPLACE FUNCTION getNextIDEmployee() 
RETURNS BIGINT 
AS 
$$
SELECT NEXTVAL('SQ_EMPLOYEE_PK')
$$ 
LANGUAGE SQL;

-- Questao 3
CREATE OR REPLACE FUNCTION getCurIDEmployee() 
RETURNS BIGINT 
AS 
$$
SELECT CURRVAL('SQ_EMPLOYEE_PK')
$$ 
LANGUAGE SQL;